/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myTokenSol from "./MyToken.sol";
export type { myTokenSol };
export type { HSBC_Coin } from "./HSBC_Coin";
